### ISSUE TITLE
Feature Request: Making Display Forks Reactive

### ISSUE THREAD

**Issue by arnabsen1729** [sadn1ck/github-repo-timeline#1]
## Description 
Enabling and disabling "Display Forks" should re actively make the necessary changes in the repo list. 

## Workaround

Currently, you are fetching all the data in Profile.vue and storing the repos in an array, and at the same time checking if `showForks` is true. 
Instead, put all the repos in the array/list and make a new bool in a repo element to indicate if its a fork or not. And then in the `Repos.vue` where you are running a `v-for` to display the repos make a check if `repo.isFork === showFork`. And yeah, you have the pass `showFork` as a prop from `Profile.vue` to `Repos.vue`

**Comment by sadn1ck** [comment]
Yes I was too lazy to do that lol, saw that I have to pass props down multiple components, and noped out. PR welcome 😂 (or I'll look into it later)
